- fract4d/c/fract4dmodule.cpp
I maintain the Fedora gnofract4d package.  We have had a number of crashes reported to us, all apparently due to bugs in the C++ code.  This patch fixes all of the issues I was able to find.  I believe that the reasons for the changes are fairly obvious, but let me know if something in here is mysterious.
> Fix several memory leaks and reference counting snafus in the C++ code.

- createdocs.py
- fract4dgui/main_window.py
- gnofract4d.desktop
> Three Minor Fixes

- doc/gnofract4d-manual/C/gnofract4d-manual.xml
- website/in/faq.html
- website/in/manual/internals.html
- website/in/manual/using.html
Use of GConf stopped some time ago.
> remove mention of GConf from documenation

- fract4d/browser_model.py
- fract4d/fc.py
- fract4dgui/browser.py
First commit is a collection of clean ups, no functional change.
Second one as its commit message:
Saves a lot of time and also exceptions when trying to display
binary files (because the type has already changed from gradient when
on_file_changed is called).
Test by selecting a gradient file in the Formula Browser and then change
to a different function type.
> Formula Browser Fixes

- fract4dgui/settings.py
Worth checking, I'm not 100% sure what it is supposed to do. It looks basically the same. Major difference is the notebook tabs are wider stretching the width.
Selected segment colour didn't work so I have hard-coded something.
Often seems there are too many segments to draw the handles, but that is not something new.
Fixes #13.
> Convert settings color page to Cairo

- fract4dgui/gtkfractal.py
Two errors:
342: TypeError: 'float' object cannot be interpreted as an integer
345: ValueError: cannot hash writable memoryview object
> fix autozoom

- fract4dgui/gtkfractal.py
With some rough timings this does appear to be faster.
Adds a need for Pycairo. This could potentially be replaced by writing a calculation for the bounding box but this is much easier.
An attempt to help with #14.
> only redraw old and new selection rectangles

- fract4dgui/dialog.py
- fract4dgui/main_window.py
- fract4dgui/settings.py
- gnofract4d.css
- setup.py
Main Window
- Make the progress bar look more like the earlier version
Fractal Settings
- Reduce the width of the notebook
- Add some space around the edges
- Display source code with monospaced font
> style using CSS

- README
> document optional manual production

- setup.py
Updates to setup.py inspired by issues reported in #34 and some tidy-ups.
Some notes in commit messages.
Tested on Gentoo with Python 3.6. I believe it will still run on Python 3.5.
> Improved checks for Python and pkg-config

- fract4d/absyn.py
- fract4d/fractlexer.py
- fract4dgui/PNGGen.py
- fract4dgui/director.py
- fract4dgui/preferences.py
- fract4dgui/settings.py
Nothing much to say, they all speak for themselves.
> Fix Three Sets of Deprecation Warnings

- fract4dgui/main_window.py
- fract4dgui/toolbar.py
Undo/Redo buttons were too big.
Took several rounds to get to the previous commit. Needed one more!
> simplify and tidy toolbar.T

- .travis.yml
I think this is correct, obviously can't test locally.
Would need access granted to Travis as per:
https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci
> add Travis configuration for CI testing

- tox.ini
> add XAUTHORITY to passenv in tox.ini

- .travis.yml
- fract4d/fractal.py
- fract4d/test_animation.py
- fract4dgui/AVIGen.py
- fract4dgui/director.py
- fract4dgui/test_director.py
- test.py
Discovered while developing the improvements in #45 but not adding anything new.
Based on #47 to run tests.
> Various fixes to existing video code

- .travis.yml
- test.py
Fixes to get tests passing with Travis.
> Working Travis

- .travis.yml
- tox.ini
Working OK for me. Let's see how Travis does...
> Run tests on Python 3.8

- .travis.yml
to tell if new checkins regress anything
> disable python 3.8 in travis config

- .mailmap
> correct .mailmap for Rachel (dx-mon)

- .mailmap
- Added Comments.
- Sorted by Appearance.
- Improved Formatting.
- Added my personal email to map.
> Improve .mailmap; sorting, formating, and add comments.

- fractutils/parfile.py
I don't use this but these are clearly out of date.
> Update fractutils for fract4d_compiler and testdata

- benchmark.py
- fract4dgui/utils.py
- mkstatic.py
- pylintrc
- test_regress.py
Best to wait until after 96 and 98 have been merged for this one, they also fix unused imports.
> Remove unused imports and enable pylint test

- fract4d/animation.py
Not found by pylint, but identified by flake8.
> Remove unused traceback import

- doc/gnofract4d-manual/C/gnofract4d-manual.xml
- fract4d/options.py
- setup.py
- website/content/_index.md
Seems like we could release an update with the recent fixes, especially the fix for running after install.
> release prep for 4.2

- README.md
- setup.py
> Update http links in README.md and setup.py to https

- bin/pylint.sh
- gnofract4d
Minor changes to get it to pass.
> Check gnofract4d executable with pylint

- .travis.yml
- tox.ini
Report linting and testing results separately. Only run pylint once.
> Run pylint as a separate job

- README.md
- fract4dgui/main_window.py
- fract4dgui/utils.py
> MacOS help

- README.md
Add the extra steps for the submodule.
> Document initializing the documentation theme submodule

- .travis.yml
- README.md
- fract4dgui/gtkfractal.py
- gnofract4d
- tox.ini
More comments in the code, fixes and tidying in README.md and some better run-time messages.
A bit more explanation in some of the commit messages.
> Improve dependency documentation

- README.md
https://github.com/fract4d/gnofract4d/blob/7e191fc44b80bd9f03bbf4553fe845cd11dd83ca/setup.py#L19
> Only need libpython3-dev as per setup.py

- fract4d/animation.py
- fract4d/colorizer.py
- fract4d/fractconfig.py
- fract4d/fractmain.py
- fract4d_compiler/cache.py
- fract4d_compiler/fc.py
- fract4d_compiler/fractlexer.py
- fract4d_compiler/fractparser.py
- fract4d_compiler/lex.py
- fract4d_compiler/preprocessor.py
- fract4d_compiler/translate.py
- fract4dgui/PNGGen.py
- fract4dgui/main_window.py
Ensure files are closed and simplify some code.
> Use 'with' statements when opening files

- MANIFEST.in
Needed for fract4d/tests/test_gradient.py.
> Add test.ase to the source distribution

- fract4d/tests/test_fract4d.py
Recent fixes to fract4dc have resolved intermittent test failures.
---
Let's see how the check goes... No, I am confident I have run this multiple times.
(Fantastic to have those fixes in - really felt like the last bit of the jigsaw after all the work to bring Gnofract4D up-to-date).
> Stop skipping testFDSite

- fract4d/animation.py
- fract4d_compiler/fractlexer.py
- fract4d_compiler/fracttypes.py
- fract4d_compiler/instructions.py
- fract4d_compiler/lex.py
- fract4dgui/gtkfractal.py
- fract4dgui/settings.py
[LGTM](https://lgtm.com) is a free code scanning service that looks for vulnerabilities and issues in the source of GitHub based projects. I have enabled this service for this repo (done from the LGTM site), which has provided this lovely list: https://lgtm.com/projects/g/fract4d/gnofract4d/?mode=list
This PR attempts to validly fix as many of these issues as is reasonable to improve code quality and provide a more solid baseline going forward. We can, if we so choose, also put a badge in the project README pointing at the project issue list, though I suspect as we do not currently show build status or code coverage, this is not something that's wanted, so I have not put anything like that in.
For now, opening as WIP as there are a lot of items to look at, evaluate and solve. For a …
> Enabled LGTM and started fixing some of the code issues it unrooted

- .github/workflows/test-gnofract4d.yml
Python 3.9 is out and I was introduced to yamllint!
> Test on released Python 3.9 and tidy YAML

- fract4dgui/utils.py
shutil.which() is available since Python 3.3.
> Remove unused utils.find_in_path()

- fract4dgui/main_window.py
- fract4dgui/shortcuts-gnofract4d.ui
- manual/content/commands.html
Common usage. Don't customise Escape.
Closes #188
> Use F11 to toggle fullscreen

- fract4dgui/main_window.py
Allows complex event processing to be removed.
---
That's the last GAction change I have.
> Use actions for arrow keys

- fract4dgui/dialog.py
- fract4dgui/settings.py
Only used once, save an import.
> Move dialog.make_label_box() to SettingsPane

- fract4dgui/director.py
Remove some unused code from director.py.
> director.py unused code

- benchmark.py
- fract4dgui/main_window.py
- fract4dgui/tests/test_main_window.py
Simplify MainWindow.__init__().
> MainWindow parameters

- fract4dgui/gtkfractal.py
- fract4dgui/main_window.py
Only used once, makes creating SubFract's simpler.
> Replace SubFract.set_master()

- fract4dgui/gtkfractal.py
- fract4dgui/utils.py
utils.input_add() only used once.
> Remove utils.input_add()

- fract4d/fractal.py
- fract4d/options.py
- fract4d/tests/test_fractal.py
Broken in:
cdcd87e ("convert options.py to use argparse", 2018-03-04)
> Fix --antialias segfaults

- fract4dgui/tests/test_DlgAdvOpt.py
- fract4dgui/tests/test_angle.py
- fract4dgui/tests/test_autozoom.py
- fract4dgui/tests/test_browser.py
- fract4dgui/tests/test_browser_model.py
- fract4dgui/tests/test_director.py
- fract4dgui/tests/test_fourway.py
- fract4dgui/tests/test_hig.py
- fract4dgui/tests/test_main_window.py
- fract4dgui/tests/test_model.py
- fract4dgui/tests/test_painter.py
- fract4dgui/tests/test_preferences.py
- fract4dgui/tests/test_renderqueue.py
- fract4dgui/tests/test_settings.py
- fract4dgui/tests/test_undo.py
Mainly new tests, a modification to the test of Application (stop running the whole program) and some unused code removal.
> Increase coverage of GUI tests

- .github/workflows/test-gnofract4d.yml
GitHub action delayed by 5 minutes or more. Let's see if this works.
> Prevent GitHub workflow delay due to brew cleanup

- .github/workflows/test-gnofract4d.yml
> Fix YAML error in test-gnofract4d.yml

- fract4dgui/AVIGen.py
- fract4dgui/DlgAdvOpt.py
- fract4dgui/PNGGen.py
- fract4dgui/autozoom.py
- fract4dgui/browser.py
- fract4dgui/director.py
- fract4dgui/director_prefs.py
- fract4dgui/hig.py
- fract4dgui/painter.py
- fract4dgui/preferences.py
- fract4dgui/renderqueue.py
Deprecated since GTK 3.10, removed in GTK 4.
> Replace deprecated Gtk.STOCK's

- fract4d/fractconfig.py
- fract4d/tests/test_fractconfig.py
- fract4dgui/preferences.py
Mainly tidying of preferences.py but also a fix to the way the compiler tab expands vertically to ensure the formula search paths get the extra space.
> Fix and Tidy Preferences

- fract4dgui/application_widgets.py
- fract4dgui/application_window.py
- fract4dgui/director.py
- fract4dgui/director_prefs.py
- fract4dgui/main_window.py
- fract4dgui/preferences.py
- fract4dgui/utils.py
Move a fair amount of code into utils.py and simplify.
> Implement file choosers as classes

- fract4dgui/AVIGen.py
- fract4dgui/DlgAdvOpt.py
- fract4dgui/PNGGen.py
- fract4dgui/angle.py
- fract4dgui/application_widgets.py
- fract4dgui/application_window.py
- fract4dgui/autozoom.py
- fract4dgui/browser.py
- fract4dgui/dialog.py
- fract4dgui/director.py
- fract4dgui/director_prefs.py
- fract4dgui/fourway.py
- fract4dgui/gtkfractal.py
- fract4dgui/hig.py
- fract4dgui/painter.py
- fract4dgui/preferences.py
- fract4dgui/renderqueue.py
- fract4dgui/settings.py
- fract4dgui/tests/test_fourway.py
- fract4dgui/tests/test_hig.py
- fract4dgui/tests/test_preferences.py
- fract4dgui/toolbar.py
- fract4dgui/utils.py
Called in main_window.py and testgui.py.
> Only need to call gi.require_version() once

- fract4d/fractconfig.py
- fract4dgui/director.py
shutil.which() has been available since Python 3.3.
> Replace fractconfig.T.find_on_path()

- fract4dgui/browser.py
- fract4dgui/gtkfractal.py
- fract4dgui/tests/__init__.py
- fract4dgui/tests/test_angle.py
- fract4dgui/tests/test_autozoom.py
- fract4dgui/tests/test_browser.py
- fract4dgui/tests/test_browser_model.py
- fract4dgui/tests/test_director.py
- fract4dgui/tests/test_director_dialogs.py
- fract4dgui/tests/test_fourway.py
- fract4dgui/tests/test_gtkfractal.py
- fract4dgui/tests/test_hig.py
- fract4dgui/tests/test_main_window.py
- fract4dgui/tests/test_model.py
- fract4dgui/tests/test_painter.py
- fract4dgui/tests/test_preferences.py
- fract4dgui/tests/test_renderqueue.py
- fract4dgui/tests/test_settings.py
- fract4dgui/tests/test_undo.py
- fract4dgui/tests/test_utils.py
- fract4dgui/tests/testgui.py
None of these files are executable so we can save some more lines.
> Remove unused python3 shebangs from GUI folder

- fract4dgui/director.py
- fract4dgui/director_dialogs.py
And a return that can be removed.
> No need to pass user_data=None to the signal handlers

- fract4dgui/application_window.py
- fract4dgui/gnofract4d.gresource.xml
Resource path $APP_ID/icons/ is always searched.
> Rename pixmaps resource directory to icons
