fract4d/gnofract4d

fract4d/browser_model.py, fract4d/cache.py, fract4d/fc.py, fract4d/test_browser_model.py, fract4d/test_fc.py, fract4dgui/angle.py, fract4dgui/autozoom.py, fract4dgui/browser.py, fract4dgui/dialog.py, fract4dgui/director.py, fract4dgui/fourway.py, fract4dgui/gtkfractal.py, fract4dgui/main_window.py, fract4dgui/painter.py, fract4dgui/preferences.py, fract4dgui/renderqueue.py, fract4dgui/settings.py, fract4dgui/test_browser.py, fract4dgui/test_director.py, fract4dgui/test_fourway.py, fract4dgui/test_main_window.py, fract4dgui/test_painter.py, fract4dgui/test_preferences.py, fract4dgui/test_renderqueue.py, fract4dgui/test_settings.py
I'd seen various bits of odd behaviour, first with the fourway's leading to a89e39cb8a8990e12ef674f6ed3d24363ece0ef0.
Also GTK+ Critical errors on the command line and Python exceptions. 
And something strange in the code:
https://github.com/edyoung/gnofract4d/blob/572dbeecde9cef266167a479368675c710e77926/fract4dgui/browser.py#L162-L163
I can't find any other examples of testing the existence of GtkTreeSelection, indeed the GTK+ docs say:
"The GtkTreeSelection object is automatically created when a new GtkTreeView widget is created, and cannot exist independently of this widget."
I think this is all the result of a confusion of classes, objects, static methods and scope. This set attempts to fix that.
There are a couple of improvements too:
- The formula browser now opens with the current …
=> Dialog Objects

createdocs.py, doc/gnofract4d-manual/C/gnofract4d.xsl
xsltproc will use the system catalog to find the local path.
Pass --nonet option to ensure the Internet is not used.
---
On Gentoo I was doing:
```
-<xsl:import href="/usr/share/sgml/docbook/stylesheet/xsl/nwalsh/xhtml/docbook.xsl"/>
+<xsl:import href="/usr/share/sgml/docbook/xsl-stylesheets/xhtml/docbook.xsl"/>
<xsl:template match="guimenuitem">
<span class="guimenuitem"><xsl:call-template name="inline.charseq"/></span>
</xsl:template>
```
Ubuntu is using a symlink, but this I believe would work everywhere (tested on Gentoo and Ubuntu) that has XML catalogs setup.
=> use universal location for docbook.xsl

fract4d/test_symbol.py, setup.py
Descriptions in the commits. New code present since at least Python 3.3.
Just silencing noise for now, although the setup.py one will be needed for Python 3.8! (All the tests are passing for me with Python 3.7).
=> Fix Python deprecation warnings

fract4d/test_image.py
The test provokes an error and checks the message.
If you don't have the system in english the test fails.
Now the test only checks part of the message text so the
language shouldn't be a problem.
=> Fix fract4d/test_image.py

README, fract4d/fractconfig.py, fract4d/test_codegen.py, fract4d/test_fc.py, fract4d/testbase.py, fract4dgui/testgui.py
There were some errors on fractconfig implemenation preventing the compiler to get the right flags for MacOS system.
Also some tests wasn't checking the environment to create the userConfig object.
Finally there was a problem with codegen (a module used for the compiler) test: it was looking for "-nan" values but, depending on the system compiler, those values could be "nan" or "-nan".
=> Fix macos compatibility

.mailmap
In this commit I have created a mailmap taken from the command:
```
( git log  --format="%aN <%aE>" --reverse ; git log  --format="%cN <%cE>" --reverse ) | perl -e 'my %dedupe; while (<STDIN>) { print unless $dedupe{$_}++}'
```
Please review the `.mailmap` file included in this pull request.
=> add .mailmap file to cleanup names in commits

README.md, setup.py
There is no minimal C++ compiler version required and C++98 std is being used as default std in GCC versions prior to 6.1, so a new flag is added in the building phase to allow to support newer C++ language standards as used in #85.
Update the readme with info about pylint (more info #66).
=> Add -std=c++17 building flag and update readme

README.md, doc/gnofract4d-manual/C/gnofract4d-manual.xml, fract4d/options.py, fract4dgui/createdocs.py, setup.py, test.py, tox.ini, website/content/_index.md
I'd like to make a 4.1 release soonish. This updates the version number in the code and tweaks the tests that check it is consistent.
=> release prep

MANIFEST.in
A distribution like Gentoo Linux wants to be able to run the tests themselves.
I removed the tests from the installation and missed this...
=> Include tests in the source distribution

createdocs.py, fract4dgui/createdocs.py
These are needed when building the package on Gentoo. I've added a comment to the code.
=> Allow documentation to be built in a non-graphical environment

.coveragerc, .gitignore, tox.ini
Test coverage is quite good, 79% with a lot of files over 90%, the overall number brought down by a few specific  files.
I suggest enabling reporting to keep it high.
I like the Coveralls service which can be hooked up to GitHub and provide browesable results and noitfications that can be used as PR checks https://coveralls.io/.
=> Enable pytest coverage checking

pylintrc
As pylint is now part of the travis scripts:
```yaml
script:
- ./bin/pylint.sh || travis_terminate 1;
- tox
```
We need to exclude the automatically generated files `lextab.py` and `parsetab.py` to pass the tests because they do not conform to the rules being checked.
Those files were removed from the repo in #55 by mistake (preventing the application to work when installed) and reintroduced in  #93 to fix that problem.
NOTE: At this moment travis is not working on this repo, see #92.
=> Exclude parsetab and lextab from pylint

fract4d_compiler/tests/test_symbol.py, pylintrc
singleton-comparison (C0121):
Comparison to %s should be %s Used when an expression is compared to singleton values like True, False or None.
=> Add pylint singleton-comparison check

fract4d/tests/test_fract4d.py
see #107 
Note that I've removed the `fract4dc.interrupt(site)`since the test is reading messages util the "fractal is done" message is received.
Also we don't need to repeat pf_load and pf_create on every iteration.
Now we use the same strategy as in `gtkfractal.py` (buffering the message parts until we have the whole) plus we use `select` package to set a timeout in case C++ crashes to not to keep waiting forever.
While I was writing this message, I found the test failed because of the condition "no one on the other side", meaning C++ crashed somehow or I did something wrong :/
https://travis-ci.com/github/HyveInnovate/gnofract4d/jobs/335546177
=> Fix #107: wait until fd has something to read or fail

examples/README.md, examples/cpp/CMakeLists.txt, examples/cpp/Dockerfile, examples/cpp/mp_double.h, examples/cpp/mp_formula.cpp, examples/cpp/mp_mandelbrot.sh
I've added a new example using a wrapper for the [MPFR](https://www.mpfr.org/) library.
The formula now is written in C++, so I had to change a bit the examples infrastructure.
The idea behind this is example is to replace the double type in the formula sources (generated by the fract4d_compiler package) by a new custom type. This new custom type is a wrapper for the MPRF types and functions with operator overload. Having this, the modifications we have to apply to the original formula source are minimal.
Cmake configuration now includes (for all examples) debug information: elapsed time, compiler information and command verbosity. Thus we can compare the different examples.
This is one approach we can investigate for #77
=> Arbitrary precision formula experiment

doc/mathlibs.md, examples/README.md, examples/cpp/CMakeLists.txt, examples/cpp/Dockerfile, examples/cpp/benchmark.cpp, examples/cpp/mp_benchmark.sh, examples/cpp/mp_double.h, examples/cpp/mp_formula.cpp
Uses Google benchmark library. Need to rearrange the docker stuff, it recompiles the benchmark library every time which slows things down a lot.
Run the benchmark with `examples/cpp/mp_benchmark.sh`
Sample output:
```
Running ./example
Run on (4 X 2700 MHz CPU s)
CPU Caches:
L1 Data 32 KiB (x2)
L1 Instruction 32 KiB (x2)
L2 Unified 256 KiB (x2)
L3 Unified 3072 KiB (x1)
Load Average: 2.38, 1.75, 1.11
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
***WARNING*** Library was built as DEBUG. Timings may be affected.
----------------------------------------------------------------------
Benchmark                            Time             CPU   Iterations
--------------------------------------------------------------------- …
```
=> Starting point for a benchmark to compare multiple-precision libs

docker/bin/run_test.sh, examples/cpp/multithread_mandelbrot.cpp, examples/cpp/simple_mandelbrot.cpp, fract4d/c/fract4dc/calcargs.cpp, fract4d/c/fract4dc/calcargs.h, fract4d/c/fract4dc/calcs.cpp, fract4d/c/fract4dc/controllers.cpp, fract4d/c/fract4dc/controllers.h, fract4d/c/fract4dc/functions.cpp, fract4d/c/fract4dc/pysite.h, fract4d/c/fract4dc/workers.cpp, fract4d/c/fract4dmodule.cpp, fract4d/c/model/MTFractWorker.cpp, fract4d/c/model/STFractWorker.cpp, fract4d/c/model/calcfunc.cpp, fract4d/c/model/calcfunc.h, fract4d/c/model/calcoptions.h, fract4d/c/model/color.h, fract4d/c/model/fractfunc.cpp, fract4d/c/model/fractfunc.h, fract4d/c/model/pointfunc.cpp, fract4d/c/model/pointfunc.h, fract4d/c/model/stats.cpp, fract4d/c/model/worker.cpp, fract4d/c/model/worker.h, fract4d/fractal.py, fract4d/tests/test_fractal.py
No (intended) behavior change in this PR, perhaps some minor improvements (loops, temp vars, repeated/unneeded operations).
- New entity "calcoptions" to avoid carrying all its properties as constructor parameters for underneath classes.
- Introduced the use of unique_ptr as well as reviewed some class initializations to simplify.
- remove some unused/unreachable code.
- rename and reorganize members for some classes to clarify public interfaces and the use of private members.
- introduced some std utilities like vector.
- started working towards SOLID principles (specially "single responsibility")
- update old fashion idioms like c-style type casting 
- ...
\* for this PR I want to keep the current fract4dc interface. This impedes some decoupling (at least without introducing more …
=> C++ Engine refactor

fract4dgui/main_window.py
@mindhells does that work on MacOS?
I spent too much time looking at the content of the dialog and didn't spot I had used show().
=> Use run() with aboutDialog

fract4d/c/fract4dc/pysite.cpp, fract4d/c/model/MTFractWorker.cpp, fract4d/c/model/imagereader.cpp, fract4d/c/model/imagewriter.cpp, fract4d/c/model/site.cpp
Please check - I'm just following the compiler messages.
=> Fix unused variable and extra ‘;’ warnings

fract4d/__init__.py, fract4d/c/fract4dmodule.cpp, setup.py
Complicated story: at runtime, we load a generated shared
object containing the code for the fractal. We want that to
be able to call some helper functions that are contained in
the fract4dc module. That module is also dynamically loaded,
and by default Python loads it without specifying RTLD_GLOBAL.
That means functions in it are not visible to other dynamically
loaded modules, which we need.
Originally I resolved this with a terrible hack: create another .so
containing the code I wanted, and dlopen() that specifically
with RTLD_GLOBAL. Looks like there is an easier fix, using
sys.setdlopenflags, which I never realized. Thanks @mindhells !
This simplifies things by removing that extra complication. Sweet.
=> remove fract4d_stdlib

.github/workflows/test-gnofract4d.yml, tox.ini
With all the problems with Travis here is an attempt to use GitHub actions instead. Let's see if the PR works. One advantage - it is easier to re-run when there is a segfault...
It does clash with #141. So, would need to be updated.
=> Use GitHub Actions instead of Travis

examples/cpp/benchmark.cpp, examples/cpp/custom_formula.cpp, examples/cpp/raw_mandelbrot.cpp, fract4d/c/fract4dc/functions.cpp, fract4d/c/fract4dc/utils.cpp, fract4d/c/model/MTFractWorker.cpp, fract4d/c/model/STFractWorker.cpp, fract4d/c/model/fractfunc.cpp, fract4d/c/model/fractfunc.h, fract4d/c/model/fractgeometry.h, fract4d/c/model/worker.h
The idea is to remove the coupling between those 2 and it looks like the reason for the coupling to exist in the 1st place is `fractFunc` holding too many responsibilities.
One of those responsibilities is managing the geometry of the fractal, that's been moved to an specific class `fract_geometry`.
That geometry information is now pulled by `STFractWorker` from a new interface `IWorkerContext` so there's no need for it to be a friend of fractFunc anymore or even know about it.
In order for that to work, fractFunc must inherit from IWorkerContext. This means a little extra cost comes with the virtual functions. I've been thinking about using [CRTP](https://en.wikipedia.org/wiki/Curiously_recurring_template_pattern) or even different patterns like "dependency injection" to solve this, but …
=> Decouple fractFunc and STFractWorker

docker/Dockerfile, docker/bin/run_builds.sh, docker/bin/run_tox.sh, examples/cpp/CMakeLists.txt, fract4d/c/fract4dc/arenas.cpp, fract4d/c/fract4dc/calcs.cpp, fract4d/c/fract4dc/colormaps.cpp, fract4d/c/fract4dc/controllers.cpp, fract4d/c/fract4dc/functions.cpp, fract4d/c/fract4dc/images.cpp, fract4d/c/fract4dc/loaders.cpp, fract4d/c/fract4dc/pysite.cpp, fract4d/c/fract4dc/pysite.h, fract4d/c/fract4dc/sites.cpp, fract4d/c/fract4dc/utils.cpp, fract4d/c/fract4dc/workers.cpp, fract4d/c/fract4dmodule.cpp, fract4d/c/fract_stdlib.cpp, fract4d/c/model/MTFractWorker.cpp, fract4d/c/model/STFractWorker.cpp, fract4d/c/model/fractfunc.cpp, fract4d/c/model/image.cpp, fract4d/c/model/imagereader.cpp, fract4d/c/model/imagewriter.cpp, fract4d/c/model/site.cpp, fract4d/c/model/site.h, fract4d/c/model/threadpool.h, fract4d/c/model/worker.h, fract4d/fractconfig.py, setup.py
So I started this to clean up some unneeded code in the workers, but then I got enthused and ended up adding some extra cleanings and tidying up:
- removed `_REENTRANT` define (see https://stackoverflow.com/questions/2601753/what-is-the-reentrant-flag)
> So it seems like _REENTRANT is mostly a no-op, these days. It might once have declared a lot of new functions, such as strtok_r; but these days those functions are mostly mandated by various decades-old standards (C99, POSIX 95, POSIX.1-2001, etc.) and so they're just always enabled.
- conditionally compile the experimental code in `STFractWorker`
- conditionally compile the `pixel_changed` callback interface for `Site` (this is meant for debug purposes only)
- narrow down the public interface of the `IFractWorker`
- added some extra …
=> Fract4dc cleanup

.github/workflows/test-gnofract4d.yml, fract4dgui/utils.py
I found this by running on a machine that didn't have xdg-open installed. With this change it could start a web browser.
The change removes the Mac specific code, @mindhells if you can check it still works, thanks.
=> Remove dependency on xdg-open for launching browser

docker/Dockerfile
This results in a Docker image that is about 200MB smaller for me (gtk3.0 seemed to be interpreted as something that needed every mono package going!) and supports the new way of launching a browser.
=> Tidy Dockerfile and add support for Gio.AppInfo.launch_default_for_uri()

fract4dgui/tests/test_main_window.py
Leftover from the switch from yelp to html only for the manual.
=> No need to stop unused yelp at the end of MainWindow tests

.github/workflows/test-gnofract4d.yml
synchronize seems to be the best event for running PRs on changes (it is actually the default). GitHub does now seem to be deduplicating the Pushes/PRs? (not a bad idea to tidy up anyway) but it doesn't catch force pushes.
=> Only run workflow on pushes to master and PR synchronize

README.md
The stable version of hugo for linux doesn't support Sass/SCSS so you need to install the extended version like is written in [the documentation of hugo](https://gohugo.io/getting-started/installing/#snap-package).
=> Add hugo extended version into README

README.md
pip ensures the data files are installed in the expected locations and
not e.g. in an egg. It is also easier to use
---
Don't suggest sudo with pip
It is not a requirement and should be a user decision.
---
Based on the experience with issue #126. Plus a new one on sudo.
=> Recommend pip for installation instead of setup.py

fract4d/c/fract4dc/calcargs.cpp, fract4d/c/fract4dc/calcs.cpp, fract4d/c/fract4dc/calcs.h, fract4d/c/fract4dc/controllers.cpp, fract4d/c/fract4dc/functions.cpp, fract4d/c/fract4dc/images.cpp, fract4d/c/model/site.cpp, fract4d/c/model/site.h
Address issues detected with UBSAN ASAN TSAN
I've already managed to find one: https://github.com/fract4d/gnofract4d/issues/73#issuecomment-657593091
Having #133 would help thanks to [Menson ability to add sanitizers out of the box](https://github.com/fract4d/gnofract4d/pull/133#issuecomment-655464733)
=> fract4dc sanitize

.github/workflows/test-gnofract4d.yml, README.md
An upgrade to v1.0.12 at the current time.
----
The v1 tag has to be moved manually in the Codecov repository, when we started using Actions it was pointing at an old version. So, this is an upgrade now and hopefully will move with new major releases in future. We haven't been getting the reports added to our PRs - will this fix it?
(And a documentation commit for macOS)
=> Change Codecov GitHub Action dependency to v1

fract4d/c/fract4dc/calcs.cpp
This code is in a thread not created by python, so it does not acquire the GIL by default.  The delete statement in question drops references to multiple python objects, possibly causing them to be deallocated while not holding the GIL.  This appears to be the direct cause of https://github.com/fract4d/gnofract4d/issues/164.
=> Hold the GIL while deleting python objects

fract4d/tests/test_formsettings.py, fract4d/tests/test_gradient.py
Directly test RGBtoHSV() and HSVtoRGB().
Use a formula with all parameter types and mock random() to fully test
formsettings mutate().
---
Based on the codecov results from #170, maybe there are others.
=> Fix inconsistent test coverage due to use of random()

fract4d/fractal.py, fract4d/tests/test_fractal.py, fract4d/tests/test_gradient.py
Some more tests to stop fluctuating coverage. And fix what looks like a bug where angle_random() was never returning -pi/2:
https://github.com/fract4d/gnofract4d/blob/5aaad2ae1d98bada86b0f16d3b3cbaff51150c4c/fract4d/fractal.py#L653-L658
=> Fix more inconsistent test coverage due to use of random()

.github/workflows/test-gnofract4d.yml
I've tried to minimise the number of checks.
Unfortunately it seems you do have to give the full version for pre-release versions of Python.
=> Test on Python 3.8 and 3.9

fract4d/tests/test_fract4d.py
Copied from fract4dgui.gtkfractal.Hidden.onData().
---
This does fix some problems, not convinced it does everything though.
onData seems to just discard messages of the wrong size:
https://github.com/fract4d/gnofract4d/blob/5aaad2ae1d98bada86b0f16d3b3cbaff51150c4c/fract4dgui/gtkfractal.py#L175-L186
I don't know if anyone has any better insight. Else, if the test failures are blocking other work then going back to skipping by reverting a6b74ac16ab7 would probably be best.
=> Make testFDSite more robust by limiting message bytes read

fract4d/fractmain.py
exist_ok was introduced in Python 3.2.
Also no need to obtain the length of the directory name.
=> Fix --buildonly with an existing directory

fract4dgui/tests/test_main_window.py
When running tests on Gentoo Linux it is not possible to specify a
dependency on "a web browser".
=> Only test showing help contents if a browser is installed

fract4dgui/main_window.py, gnofract4d
MainWindow.on_fractal_change() was being called several times while the
first fractal was being created.
Prevents application hangs on startup since:
47752e0 ("Hold the GIL while deleting python objects", 2020-08-16)
---
Please check and test, I haven't looked at this code before and got here by experimentation.
=> Only draw once on application startup

fract4d/c/fract4dc/calcargs.cpp, fract4d/c/fract4dc/calcs.cpp, fract4d/c/fract4dmodule.cpp
See #177 for more details.
> Basically here I'm releasing the interpreter lock immediately instead of waiting for site->wait when fract4dc.calc is called, so the other thread can acquire it.
I've removed the calcargs ref_count mutex as we don't need it since we are doing ref_counting always in the interpreter thread.
Also I created a struct for the GIL acquisition so we can benefit from the RAII pattern.
=> Prevent GIL deadlock

README.md, fract4dgui/main_window.py
GTK 3.22 is present in Ubuntu 18.04 LTS (which we are using in GitHub Actions). Debian stable has GTK 3.24.
What is the minimum OS we want to support? Raising the minimum Python to 3.6 has already ruled out Ubuntu 16.04 LTS (which ends support in April 2021).
GtkShortcutsShortcut:action-name would be useful for some work I am just about to post.
=> Raise minimum GTK to 3.22 and fix Gdk.Screen deprecation warnings

fract4dgui/main_window.py, fract4dgui/shortcuts-gnofract4d.ui
I copied the method comment instead of the description for the user from Save High-Res Image.
Also:
Remove unused MainWindow.get_all_actions()
Not used since:
ae9f710 ("Change documentation to markdown (#101)", 2020-06-07)
(fract4dgui/createdocs.py was deleted)
=> Correct title of Save High-Res Image shortcut

fract4dgui/director.py, fract4dgui/director_prefs.py, fract4dgui/main_window.py, fract4dgui/tests/test_director.py, fract4dgui/tests/test_director_prefs.py, fract4dgui/utils.py
Use "Save" and "Open" labels instead of "OK".
Stock labels are deprecated.
---
Also remove unused utils.get_file_chooser_extra_widget()
=> Set defaults in FileChooserDialogs and replace stock labels

benchmark.py, fract4dgui/director.py, fract4dgui/main_window.py, fract4dgui/shortcuts-gnofract4d.ui, fract4dgui/tests/test_main_window.py, fract4dgui/tests/test_model.py, fract4dgui/tests/test_undo.py, fract4dgui/toolbar.py, fract4dgui/ui.xml, fract4dgui/undo.py, gnofract4d, pytest.ini
WIP because it includes a couple of other PRs and so would be rebased and even changed if we stick at GTK 3.18.
One new feature which is enforcing uniqueness i.e. only one copy of Gnofract 4D can run at a time (is there a case for running more than one?).
Mainly fixing GTK deprecation warnings with an eye on GTK 4. Replacing Gtk.UIManager, including translating the menu XMLs into GMenuModel representations that will be the only format for the future.
Closes #44.
=> Replace use of deprecated Gtk.UIManager

fract4dgui/preferences.py
Give space to the entries not labels.
=> Fix expanding preferences dialog compiler tab

doc/formula_sharing.md, fract4d/c/model/site.cpp, fract4dgui/browser.py, fract4dgui/gtkfractal.py, fract4dgui/main_window.py, fract4dgui/preferences.py, fract4dgui/settings.py, fract4dgui/tests/test_utils.py, fract4dgui/utils.py, tox.ini
RFC doc ought to be in another PR but oh well
=> Bugfix for adjusting parameter values

.github/codecov.yml
Coverage requires Mac and Linux testing.
Don't fail check for small decreases in coverage.
=> Configure Codecov to wait for all results and set threshold

fract4dgui/main_window.py
Replace MainWindow.attach_subfract() with a loop
No need to set default scroll policy on Gtk.ScrolledWindow
https://developer.gnome.org/gtk3/stable/GtkScrolledWindow.html#GtkScrolledWindow--hscrollbar-policy
https://developer.gnome.org/gtk3/stable/GtkScrolledWindow.html#GtkScrolledWindow--vscrollbar-policy
---
Nothing new, just simplify MainWindow a little.
=> Improve MainWindow.create_fractal()

fract4dgui/angle.py, fract4dgui/application_window.py, fract4dgui/browser.py, fract4dgui/fourway.py, fract4dgui/gtkfractal.py, fract4dgui/main_window.py, fract4dgui/preferences.py, fract4dgui/tests/test_angle.py, fract4dgui/tests/test_fourway.py, fract4dgui/tests/test_utils.py, fract4dgui/toolbar.py, fract4dgui/utils.py
Gtk.Toolbar will go in future, and in fact replacing it with a Gtk.Box allows some simplification.
Also take advantage of the higher-level methods introduced in GTK 3 for Gtk.ComboBoxText to remove the menu model code.
Rename utils.create_option_menu() to combo_box_text_with_items().
=> Replace Gtk.Toolbar, deprecated for GTK 4

.github/workflows/test-gnofract4d.yml, .gitignore, README.md, bin/resources.sh, fract4dgui/application_window.py, fract4dgui/builder/help-overlay.ui, fract4dgui/builder/menus.ui, fract4dgui/director.py, fract4dgui/gnofract4d.gresource.xml, fract4dgui/main_window.py, fract4dgui/tests/test_director.py, fract4dgui/tests/test_main_window.py, setup.py
Advantages:
* Gtk.Application loads menus and the shortcuts window definitions automatically.
* 5 files: menus, shortcuts, CSS and the two remaining pixmaps can be combined into one file that is less than half the size of the uncompressed menu file.
Disadvantages:
* Adds a dependency on `glib-compile-resources`, which is bundled with GLib in Homebrew and Gentoo Linux and already installed in the GitHub Actions VMs. It is available in a separate package on Debian/Ubuntu.
* If modifying any of the files during development the GResource file needs to be recreated. This can be done with either `setup.py build` or `./bin/resources.sh`.
=> Use a GResource XML file

fract4d/fractconfig.py, fract4d/tests/test_fractconfig.py, fract4d/tests/testbase.py
If the user removes _shared_formula_dir, on the next start-up
a second ${HOME}/gnofract4d/formulas was also being added.
Fixed by removing the numeric keys from the path items - order is
preserved by the dictionary containing them.
---
Split out because it changes the config file format - but includes code to automatically convert older files to make it transparent.
This one is draft because it is based on #213.
=> Fix duplicating formula_paths in user configuration

fract4dgui/AVIGen.py, fract4dgui/DlgAdvOpt.py, fract4dgui/PNGGen.py, fract4dgui/angle.py, fract4dgui/application_widgets.py, fract4dgui/application_window.py, fract4dgui/autozoom.py, fract4dgui/browser.py, fract4dgui/director.py, fract4dgui/director_prefs.py, fract4dgui/fourway.py, fract4dgui/gtkfractal.py, fract4dgui/main_window.py, fract4dgui/painter.py, fract4dgui/preferences.py, fract4dgui/renderqueue.py, fract4dgui/settings.py, fract4dgui/tests/test_DlgAdvOpt.py, fract4dgui/tests/test_autozoom.py, fract4dgui/tests/test_browser_model.py, fract4dgui/tests/test_director.py, fract4dgui/tests/test_director_prefs.py, fract4dgui/tests/test_hig.py, fract4dgui/tests/test_main_window.py, fract4dgui/toolbar.py, fract4dgui/utils.py
This works through the fract4dgui folder:
* using keyword arguments with Gtk constructors where possible
* replacing deprecated Gtk.Hbox and Gtk.Vbox
* converting instance variables to local variables where possible
* removing `pylint: disable=no-member` where possible
* enabling the whole folder to pass all flake8 tests (except E402 for files with `gi.require_`)
=> Tidy GUI folder

fract4dgui/gtkfractal.py
Has no effect and cannot be cleared.
---
Don't expect many people try using the mouse on the preview image, but just in case.
=> Prevent user drawing selection on the preview

fract4dgui/angle.py, fract4dgui/application_window.py, fract4dgui/fourway.py, fract4dgui/tests/test_angle.py
A few minor tweaks around angles:
* test_angle doesn't import testgui so does need a gi.require_version() (for angle.py)
* declare axis in the angle and fourway classes
* rename ApplicationWindow.create_angle_widget(), to be consistent with add_fourway(), and add_warpmenu(), that both create the object and add it to the toolbar.
=> Angle tweaks

fract4dgui/application_widgets.py, fract4dgui/application_window.py, fract4dgui/main_window.py
A couple of tweaks:
* Create a HiresImageSaveChooser class to be consistent with all the other file choosers in ApplicationDialogs
* Rename ApplicationWindow.bar to statusbar, clarifying what it is and matching menubar and toolbar
=> Create HiresImageSaveChooser and Rename statusbar

fract4dgui/application_window.py, fract4dgui/hig.py, fract4dgui/main_window.py, fract4dgui/settings.py
Three small fixes.
GTK 4 compatibility and Gio.resources_register() do not change the GUI.
The other commit is for the Fractal Settings, Location tab - the shorter labels and their colons were more centered than right aligned.
=> Align right settings location table labels, GTK 4 and Gio.resources_register()

fract4dgui/angle.py, fract4dgui/application_widgets.py, fract4dgui/application_window.py, fract4dgui/fourway.py, fract4dgui/gnofract4d.css, fract4dgui/tests/test_angle.py
With a 1024x768 fractal I had a blank margin down the right of the application, changing to setting margin and padding for the toolbar in CSS fixed this for me. It is also what is recommended and available in GTK 4.
The Preview fractal has more space below than above, this can be seen on macOS:
https://user-images.githubusercontent.com/1893197/102902879-72023680-4467-11eb-9541-4be960fad93b.png
Increasing the size of the Preview to 53 pixels fixes this, make this one value used by all of the toolbar items. This is just a constant here, but could be the start of making it configurable in the future.
=> Use toolbar CSS

fract4dgui/application_window.py, fract4dgui/main_window.py, fract4dgui/tests/test_main_window.py
One fix for pressing Escape causes the "Save changes" exit dialog to be reshown.
Plus some final tidying up that is the end of this sequence of changes from me.
=> Allow "Save changes" dialog to be closed by Escape

tox.ini
Avoid false positives with 2.7.
2.7.0
E1101: Instance of 'OverloadList' has no 'ret' member (no-member)
https://github.com/fract4d/gnofract4d/runs/1955404235#step:9:15
2.7.2
E1126: Sequence index is not an int, slice, or instance with `__index__` (invalid-sequence-index)
https://github.com/PyCQA/pylint/issues/4083
=> Pin pylint to version 2.6.2

fract4d/fractconfig.py
Fixes problems with file paths caused by:
3e3509e ("Fix duplicating formula_paths in user configuration (#217)", 2021-02-04)
---
I think this is OK because we don't expect the user to directly edit this file.
Fixes #239.
=> Make configuration file keys case sensitive

MANIFEST.in, setup.cfg
Fails because COPYING cannot be found and does not include new
resources.
=> Fix bdist_rpm after recent changes

.github/codecov.yml, .github/workflows/test-gnofract4d.yml, fract4d/tests/test_gradient.py
Fixes:
```py
fract4d/tests/test_gradient.py::Test::testGetCoolorUrl
/usr/lib/python3.10/unittest/case.py:549: ResourceWarning: unclosed file <_io.BufferedReader name='testdata/test.ase'>
method()
```
=> Ensure testGetCoolorUrl() closes test.ase

.github/workflows/test-gnofract4d.yml, tox.ini
Test with Python 3.11
GitHub Actions have deprecated Node 12 and macOS 10
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22/
=> Testing Updates

fract4dgui/tests/test_autozoom.py, fract4dgui/tests/test_browser.py, fract4dgui/tests/test_director.py, fract4dgui/tests/test_director_dialogs.py, fract4dgui/tests/test_hig.py, fract4dgui/tests/test_main_window.py, fract4dgui/tests/test_painter.py, fract4dgui/tests/test_settings.py, fract4dgui/tests/testgui.py
TypeError: 'NoneType' object is not callable
---
Something changed when using pytest on its own - I've seen this on other projects. You now have to have the gettext `_()` alias installed.
=> Fix tests failing with pytest due to missing _()

setup.py
[1] indirectly removed -Wstrict-prototypes by overwriting the environment CFLAGS with sysconfig.get_config_var("CFLAGS"), which is passed to the compiler anyway [2].
sysconfig.get_config_var("OPT") is included in
sysconfig.get_config_var("CFLAGS") [3].
Don't pass -O3 if CFLAGS is set because only the last -O option is used [4]. -DNDEBUG is typically present in sysconfig.get_config_var("CFLAGS").
[1]
426676c ("silenced annoying -Wstrict-prototypes warning", 2015-06-07)
[2]
https://setuptools.pypa.io/en/latest/userguide/ext_modules.html#compiler-and-linker-options
[3]
https://github.com/python/cpython/blob/351842b46a7cb3c3f23b200d532cf29e4557ad4b/Makefile.pre.in#L101
[4]
https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html
=> Respect environment CFLAGS

fract4d/c/fract_stdlib.h
This avoids test failures in generated code with C compilers that do not support implicit function declartions:
```
>           raise fracttypes.TranslationError(
"Error reported by C compiler:%s" % output)
E           fract4d_compiler.fracttypes.TranslationError: Error reported by C co
mpiler:/tmp/fract4d_4tueiy9c/gnofract4d-cache/fract4d_9ebc1853081db2ea5eb7cce846
42cd4e.c: In function ‘pf_calc’:
E           /tmp/fract4d_4tueiy9c/gnofract4d-cache/fract4d_9ebc1853081db2ea5eb7c
ce84642cd4e.c:282:1: error: implicit declaration of function ‘image_lookup’
E             282 | image_lookup(t__a_cf1image,z_re,z_im, &t__cf10, &t__cf11, &t
__cf12);
E                 | ^~~~~~~~~~~~
```
```
>           raise fracttypes.TranslationError(
"Error reported by C compiler:%s" % output)
E …
```
=> Declare image_lookup, gradient in fract_stdlib.h
